{{- if .Values.config.monitoring.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: calico-felix-monitoring
  namespace: kube-system
spec:
  ports:
    - port: {{ .Values.config.monitoring.felixMetricsPort }}
      targetPort: {{ .Values.config.monitoring.felixMetricsPort }}
  selector:
    k8s-app: calico-node
{{- end }}