---
apiVersion: {{ include "rbacversion" . }}
kind: RoleBinding
metadata:
  name: gardener.cloud:psp:calico-node-cpva
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gardener.cloud:psp:kube-system:calico-node-cpva
subjects:
  - kind: ServiceAccount
    name: calico-node-cpva
    namespace: kube-system
