{{- if .Values.config.typha.enabled }}
---
apiVersion: {{ include "rbacversion" . }}
kind: RoleBinding
metadata:
  name: gardener.cloud:psp:calico-typha
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gardener.cloud:psp:kube-system:calico-typha
subjects:
- kind: ServiceAccount
  name: calico-typha
  namespace: kube-system
{{- end }}
