{{- if .Values.config.typha.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-typha
  namespace: kube-system
{{- if .Values.useProjectedTokenMount }}
automountServiceAccountToken: false
{{- end }}
{{- end }}
