{{- if and (.Values.config.typha.enabled) (not .Values.pspDisabled) }}
---
apiVersion: {{ include "rbacversion" . }}
kind: ClusterRole
metadata:
  name: gardener.cloud:psp:kube-system:typha-cpva
rules:
  - apiGroups:
      - policy
      - extensions
    resourceNames:
      - gardener.kube-system.typha-cpva
    resources:
      - podsecuritypolicies
    verbs:
      - use
{{- end }}
