{{- if .Values.config.typha.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: calico-typha-vertical-autoscaler
  namespace: kube-system
data:
  typha-autoscaler: |-
    {
      "calico-typha": {
        "requests": {
          "cpu": {
            "base": "120m",
            "step": "80m",
            "nodesPerStep": 10,
            "max": "500m"
          },
          "memory": {
            "base": "100Mi",
            "step": "40Mi",
            "nodesPerStep": 10,
            "max": "2000Mi"
          }
        }
      }
    }
{{- end }}
