apiVersion: v1
kind: ConfigMap
metadata:
  name: calico-monitoring-config
  namespace: {{ .Release.Namespace }}
  labels:
    extensions.gardener.cloud/configuration: monitoring
data:
  scrape_config: |
    - job_name: 'felix-metrics'
      scheme: https
      tls_config:
        # This is needed because the kubelets' certificates are not are generated
        # for a specific pod IP
      {{- if .Values.useProjectedTokenMount }}
        insecure_skip_verify: true
      authorization:
        type: Bearer
        credentials_file: /var/run/secrets/gardener.cloud/shoot/token/token
      {{- else }}
{{ include "prometheus.tls-config.kube-cert-auth-insecure" . | indent 8 }}
      {{- end }}
      kubernetes_sd_configs:
      - role: endpoints
        api_server: https://kube-apiserver:443
        tls_config:
        {{- if .Values.useProjectedTokenMount }}
          ca_file: /etc/prometheus/seed/ca.crt
        authorization:
          type: Bearer
          credentials_file: /var/run/secrets/gardener.cloud/shoot/token/token
        {{- else }}
{{ include "prometheus.tls-config.kube-cert-auth" . | indent 10 }}
        {{- end }}
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        regex: calico-felix-monitoring
        action: keep
      - target_label: __address__
        replacement: kube-apiserver:443
      - source_labels: [__meta_kubernetes_pod_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/namespaces/kube-system/pods/${1}:9091/proxy/metrics
    - job_name: 'typha-metrics'
      scheme: https
      tls_config:
        # This is needed because the kubelets' certificates are not are generated
        # for a specific pod IP
      {{- if .Values.useProjectedTokenMount }}
        insecure_skip_verify: true
      authorization:
        type: Bearer
        credentials_file: /var/run/secrets/gardener.cloud/shoot/token/token
      {{- else }}
{{ include "prometheus.tls-config.kube-cert-auth-insecure" . | indent 8 }}
      {{- end }}
      kubernetes_sd_configs:
      - role: endpoints
        api_server: https://kube-apiserver:443
        tls_config:
{{ include "prometheus.tls-config.kube-cert-auth" . | indent 10 }}
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        regex: calico-typha-monitoring
        action: keep
      - target_label: __address__
        replacement: kube-apiserver:443
      - source_labels: [__meta_kubernetes_pod_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/namespaces/kube-system/pods/${1}:9093/proxy/metrics

  dashboard_operators: |
    calico-felix-dashboard.json: |-
    {{- .Files.Get "calico-felix-dashboard.json" | nindent 6 }}

    calico-typha-dashboard.json: |-
    {{- .Files.Get "calico-typha-dashboard.json" | nindent 6 }}
