{{- if and (.Values.config.kubeControllers.enabled) (not .Values.pspDisabled) }}
---
apiVersion: {{ include "rbacversion" . }}
kind: ClusterRole
metadata:
  name: gardener.cloud:psp:kube-system:calico-kube-controllers
rules:
  - apiGroups:
      - policy
      - extensions
    resourceNames:
      - gardener.kube-system.calico-kube-controllers
    resources:
      - podsecuritypolicies
    verbs:
      - use
{{- end }}