{{- if and (.Values.config.kubeControllers.enabled) (not .Values.pspDisabled) }}
---
apiVersion: {{ include "podsecuritypolicyversion" .}}
kind: PodSecurityPolicy
metadata:
  name: gardener.kube-system.calico-kube-controllers
spec:
  volumes:
    - secret
    - projected
  privileged: false
  runAsUser:
    # TODO(ialidzhikov): Switch to MustRunAsNonRoot when the arm64 image of the calico-kube-controllers
    # does no longer run as root. Ref https://github.com/projectcalico/calico/pull/6346.
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
{{- end }}