{{- if .Values.config.kubeControllers.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-kube-controllers
  namespace: kube-system
{{- if .Values.useProjectedTokenMount }}
automountServiceAccountToken: false
{{- end }}
{{- end }}
