apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: gardener-extension-networking-calico
value: 1000000000
globalDefault: false
description: "Priority class for the Gardener extension: networking-calico."